[package]
name = "sem-cli"
version = "0.3.0"
edition = "2021"

[[bin]]
name = "sem"
path = "src/main.rs"

[dependencies]
sem-core = { path = "../sem-core" }
clap = { version = "4", features = ["derive"] }
colored = "2"
git2 = "0.19"
serde_json = "1"
